<a href="https://colab.research.google.com/github/chiranjeevi-manike/Deep-Learning/blob/main/Single_Layer_vs_Multi_Layer_Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Generate sample data (XOR problem)
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [0], [0], [1]])  # AND logic gate

# Initialize weights and bias
weights = np.random.rand(2, 1)
bias = np.random.rand(1)
learning_rate = 0.1
epochs = 100

# Activation function (Step function)
def step_function(x):
    return np.where(x >= 0, 1, 0)

# Training loop
for epoch in range(epochs):
    linear_output = np.dot(X, weights) + bias
    y_pred = step_function(linear_output)

    # Compute error
    error = y - y_pred

    # Update weights and bias using the Perceptron learning rule
    weights += learning_rate * np.dot(X.T, error)
    bias += learning_rate * np.sum(error)

    if epoch % 10 == 0:
        loss = np.mean(np.square(error))
        print(f'Epoch {epoch}, Loss: {loss}')

# Prediction
print("\nFinal Predictions:")
print(step_function(np.dot(X, weights) + bias))


Epoch 0, Loss: 0.75
Epoch 10, Loss: 0.5
Epoch 20, Loss: 0.0
Epoch 30, Loss: 0.0
Epoch 40, Loss: 0.0
Epoch 50, Loss: 0.0
Epoch 60, Loss: 0.0
Epoch 70, Loss: 0.0
Epoch 80, Loss: 0.0
Epoch 90, Loss: 0.0

Final Predictions:
[[0]
 [0]
 [0]
 [1]]


In [ ]:
pip install tensorflow

In [3]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Generate sample data (XOR problem)
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])  # XOR problem

# Build MLP model
model = Sequential()
model.add(Dense(4, input_dim=2, activation='relu'))  # Hidden layer with 4 neurons
model.add(Dense(1, activation='sigmoid'))            # Output layer with 1 neuron

# Compile model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train model
model.fit(X, y, epochs=100, verbose=0)

# Prediction
predictions = (model.predict(X) > 0.5).astype("int32")

# Results
print("\nFinal Predictions:")
print(predictions)


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step

Final Predictions:
[[0]
 [1]
 [1]
 [0]]


In [ ]:
pip install torch torchvision


In [5]:
import torch
import torch.nn as nn
import torch.optim as optim

# Generate sample data (XOR problem)
X = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)
y = torch.tensor([[0], [1], [1], [0]], dtype=torch.float32)

# Define the MLP model
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.hidden = nn.Linear(2, 4)   # Input layer → Hidden layer (2 → 4)
        self.output = nn.Linear(4, 1)   # Hidden layer → Output layer (4 → 1)

    def forward(self, x):
        x = torch.relu(self.hidden(x))   # ReLU activation for hidden layer
        x = torch.sigmoid(self.output(x)) # Sigmoid activation for output layer
        return x

# Instantiate the model
model = MLP()

# Loss and optimizer
criterion = nn.BCELoss() # Binary Cross-Entropy Loss
optimizer = optim.Adam(model.parameters(), lr=0.1)

# Training loop
epochs = 1000
for epoch in range(epochs):
    optimizer.zero_grad()                # Clear gradients
    outputs = model(X)                  # Forward pass
    loss = criterion(outputs, y)         # Compute loss
    loss.backward()                      # Backward pass
    optimizer.step()                     # Update weights

    if epoch % 100 == 0:
        print(f'Epoch [{epoch}/{epochs}], Loss: {loss.item():.4f}')

# Prediction
with torch.no_grad():
    predictions = (model(X) > 0.5).float()
    print("\nFinal Predictions:")
    print(predictions)


Epoch [0/1000], Loss: 0.7279
Epoch [100/1000], Loss: 0.6931
Epoch [200/1000], Loss: 0.6931
Epoch [300/1000], Loss: 0.6931
Epoch [400/1000], Loss: 0.6931
Epoch [500/1000], Loss: 0.6931
Epoch [600/1000], Loss: 0.6931
Epoch [700/1000], Loss: 0.6931
Epoch [800/1000], Loss: 0.6931
Epoch [900/1000], Loss: 0.6931

Final Predictions:
tensor([[0.],
        [0.],
        [0.],
        [0.]])
